# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            A webblog
tagline:          'A Jekyll theme'
description:      '刘浩，又一个程序员<br>我的座右铭:<br>世界上只有一种英雄主义,就是看清生活的真相之后依然热爱生活'
url:              http://haolly.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0
gems:
   - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
   - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
   - jekyll-paginate

github:
  repo:           https://github.com/haolly

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: haolly
# excerpt_separator: "<!--excerpt-->"
